### ISSUE TITLE
Add support for Web Share Target API

### ISSUE THREAD

**Issue by flunderpero** [GoogleChrome/android-browser-helper#66] opened 2020-02-13 21:27 UTC
It is possible to register a PWA (WebAPK) as share target (it happens automatically if `share_target` is specified in `manifest.json`) but it does not seem to be supported in TWA at the moment.
This is a huge bummer for us because share data with our PWA/TWA is a central feature.

**Comment by PEConn** [comment] 2020-02-14 09:24
For context, we do have support for Share Target landed in the `experimental` branch (https://github.com/GoogleChrome/android-browser-helper/commit/223a17cddba56ecbdf773f39a3faa1ef5c46c8e9), the reason we then reverted it on master was because the necessary APIs hadn't made their way into `androidx.browser` yet.

The APIs are now in `androidx.browser` so adding share support should just be a matter of relanding that CL.

**Comment by flunderpero** [comment] 2020-02-14 09:37
That's great news! I just discovered the commit reverting the changes (https://github.com/GoogleChrome/android-browser-helper/commit/5f6d124afa28b1693bc2f047f570656a06d057a6) just before reading your comment.

Do you have a timeline on when it will land in master and be released?

**Comment by PEConn** [comment] 2020-02-17 13:55
@andreban Do you reckon it's worth adding this issue to a milestone (1.1.0 maybe?)?

**Comment by andreban** [comment] 2020-02-17 14:30
Sounds good. Created a 1.2.0 milestone (1.1.0 was FocusActivity and is already out)

**Comment by PEConn** [comment] 2020-02-18 16:14
Along with this, we should also merge in the immersive mode changes (https://github.com/GoogleChrome/android-browser-helper/pull/25).

**Comment by flunderpero** [comment] 2020-04-06 10:05
I created a PR (#83), but still have some weird issues (see PR). Perhaps any of you could give me hint?

**Comment by flunderpero** [comment] 2020-04-27 17:16
Two and a half months and a PR later and still there is no progress on this. We cannot release our app, because its main benefit is being a share-target, which works absolutely great as a PWA. But our customers demand an app (and we want to have the benefits of being listed in the Play Store).

I am a bit baffled that we seem to be the only ones desperately missing this feature. 

I don't want to sound pi**ed or blame anyone for anything, but I need a perspective going forward. Had I known 2.5 months ago, that support for WebShareTargetV2 is not coming for months, I would have decided to use Cordova or write a wrapper on my own. 

It would be great if you could just give me feedback, whether you plan to work on this in the next couple of weeks. I would love to help out (more), but my knowledge of the inner workings of this project and androidx is at its limit. :-)

**Comment by andreban** [comment] 2020-04-28 09:28
Hey @flunderpero,

I understand your frustration and we *really* appreciate your effort on cherry picking the Web Share Target implementation and updating it. 

I'm sorry we didn't get back sooner. The issue is not immediately obvious to us and we will need dig deeper to find out why it doesn't have the expected behaviour, which we just didn't have time to do so yet. We should have flagged this and set expectations sooner.

Web Share Target is definitely on our radar, as is locking screen orientation or starting the app in immersive mode, among other issues. But, as is usually true in software engineering, there are limited resources and we're trying to prioritise what to solve first. Your feedback and the feedback from many other developers is definitely taken into account when discussing that.

**Comment by PEConn** [comment] 2020-07-23 10:26
Hey, do you mind checking if the bug still occurs on Chrome Canary 86.0.4208.0 or above?

**Comment by flunderpero** [comment] 2020-07-23 13:04
I just tested it with 86.0.4208.3 and all's still the same.

**Comment by PEConn** [comment] 2020-07-24 10:15
Ah damnit, I'd hoped that
https://chromium-review.googlesource.com/c/chromium/src/+/2302759 had fixed
it.

Oh well, I'll dig further.

**Comment by greyGuy11** [comment] 2020-08-25 09:47
Is there any schedule for share target? I'm so missing this feature.

**Comment by mvano** [comment] 2020-10-16 15:24
This has basically landed now in #160 but there seems to be some issue that is not happening on all devices, as discussed in #83. I'd like to close that PR though, and focus the discussion in this issue. I'll try some different configurations, emulators, devices, and os versions to see if I can reproduce the issue. @flunderpero is there any exception in logcat that might be relevant?

**Comment by flunderpero** [comment] 2020-10-26 16:06
I have our app with #160 working for the past week or so. Up until now I did not run into any issue regarding the WebShare Target API. That is, I am able to share content (images for the most part) with the app whether the app had been open beforehand or not. I rolled out this version to our internal test group and keep you posted. So far everything looks good!

**Comment by greyGuy11** [comment] 2020-11-11 10:07
I tried last release 2.0.1 with bubblewrap, and it still doesn't work. If I want to share simple link from browser my app doesn't appear on list to share. It works only if my app is installed as PWA.

**Comment by andreban** [comment] 2020-11-11 10:47
@greyGuy11 we haven't released a Bubblewrap version that supports Web Share Target yet and it support should land in version `1.8.0`. Could you try the canary version of Bubblewrap to try it out (currently, [1.8.0-alpha.1](https://www.npmjs.com/package/@bubblewrap/cli/v/1.8.0-alpha.1)) and let us know if it works?

**Comment by greyGuy11** [comment] 2020-11-11 17:41
@andreban I just tried 1.8.0-alpha.1 and unfortunately no difference.

**Comment by andreban** [comment] 2020-11-11 17:50
Can you share the generated twa-manifest.json?

**Comment by greyGuy11** [comment] 2020-11-11 18:57
```
{
  "packageId": "com.mydevco.myapp.twa",
  "host": "myapp.app",
  "name": "MyApp",
  "launcherName": "MyApp",
  "display": "standalone",
  "themeColor": "#FFFFFF",
  "navigationColor": "#000000",
  "navigationColorDark": "#000000",
  "navigationDividerColor": "#000000",
  "navigationDividerColorDark": "#000000",
  "backgroundColor": "#FFFFFF",
  "enableNotifications": false,
  "startUrl": "/?utm_source=pwa",
  "iconUrl": "https://myapp.app/assets/img/icons-512.png",
  "splashScreenFadeOutDuration": 300,
  "signingKey": {
    "path": "./android.keystore",
    "alias": "android"
  },
  "appVersionName": "1",
  "appVersionCode": 1,
  "shortcuts": [],
  "generatorApp": "bubblewrap-cli",
  "webManifestUrl": "https://myapp.app/manifest.json",
  "fallbackType": "customtabs",
  "features": {},
  "alphaDependencies": {
    "enabled": false
  },
  "enableSiteSettingsShortcut": true,
  "isChromeOSOnly": false,
  "orientation": "default",
  "appVersion": "1"
}
```
Of course there is real domain instead of myapp.app.
Do you also need content of web manifest.json?

**Comment by AliasIO** [comment] 2020-12-15 03:10
I'm waiting for this too, tried with 1.8.0-alpha.23 and no luck.

**Comment by AliasIO** [comment] 2020-12-17 00:06
@andreban I noticed that `share_target.params.files` is required in `manifest.json` (I believe this should be optional). Adding that, `shareTarget` is correctly added to twa-manifest.json using @bubblewrap/cli@1.8.0.

However, after installing the app on my phone I still can't share to it. When I install the app as a PWA from Chrome, it works fine.

```
{
  "packageId": "com.wappalyzer.twa",
  "host": "twa.wappalyzer.com",
  "name": "Wappalyzer",
  "launcherName": "Wappalyzer",
  "display": "standalone",
  "themeColor": "#32067C",
  "navigationColor": "#000000",
  "navigationColorDark": "#000000",
  "navigationDividerColor": "#000000",
  "navigationDividerColorDark": "#000000",
  "backgroundColor": "#FFFFFF",
  "enableNotifications": false,
  "startUrl": "/?standalone=true",
  "iconUrl": "https://twa.wappalyzer.com/images/logo/icon_512.png",
  "maskableIconUrl": "https://twa.wappalyzer.com/images/logo/icon_mask_512.png",
  "monochromeIconUrl": "https://twa.wappalyzer.com/images/logo/icon_white_512.png",
  "splashScreenFadeOutDuration": 300,
  "signingKey": {
    "path": "***",
    "alias": "android"
  },
  "appVersionName": "1",
  "appVersionCode": 1,
  "shortcuts": [],
  "generatorApp": "bubblewrap-cli",
  "webManifestUrl": "https://twa.wappalyzer.com/manifest.json",
  "fallbackType": "customtabs",
  "features": {},
  "alphaDependencies": {
    "enabled": false
  },
  "enableSiteSettingsShortcut": true,
  "isChromeOSOnly": false,
  "shareTarget": {
    "action": "https://twa.wappalyzer.com/",
    "params": {
      "title": "title",
      "text": "text",
      "url": "url",
      "files": []
    }
  },
  "orientation": "default",
  "appVersion": "1"
}
```

**Comment by andreban** [comment] 2021-02-05 15:52
This is being tracked on the Bubblewrap repo at https://github.com/GoogleChromeLabs/bubblewrap/issues/451

**Closed by andreban** 2021-02-05 15:52 UTC
Labels: enhancement
