### ISSUE TITLE
Payment Provider Demo Not Working: "serviceworker" must be a dictionary

### ISSUE THREAD

**Issue by limhenry** [GoogleChrome/android-browser-helper#98] opened 2020-05-16 10:51 UTC
The Payment Provider [demo](http://beer.conn.dev/) is not working. The service worker file is missing from the demo.

![Screen Shot 2020-05-16 at 5 50 10 PM](https://user-images.githubusercontent.com/4544770/82117902-b88b0680-979d-11ea-822a-ad52339cede8.png)

**Comment by PEConn** [comment] 2020-05-20 13:25
Hey Henry,

Thanks for pointing out that warning, I'll see to it when I have a more solid understanding of the moving parts required for Web Payments. (I think the serviceworker is required for Web Payments in general, but not necessary for the TWA integration we're working on.)

Having said that, it is a warning and not an error. The page does still work (for me at least, despite the warning), when running from the [payment-provider][1] demo.

The payment stuff at the moment is fairly new and reasonably untested, so do be wary. (However, any help trying it out and finding bugs is greatly appreciated.)

[1]: https://github.com/GoogleChrome/android-browser-helper/tree/master/demos/payment-provider

**Comment by limhenry** [comment] 2020-05-27 14:56
(sorry for late reply)

Weirdly, the demo is not working for me (the Google Play Payment popup won't appear, and I will get the sw error and the "no enrolled instrument" error). 

However, I did clone your website and added the service worker myself, and the Google Play Payment will appear.

**Comment by PEConn** [comment] 2020-05-27 15:47
I think once launched, we won't need a Service Worker and we can just set the Payment Provider to `com.google.play.billing` (or something like that), so that may be why my site is in an inconsistent state. (Maybe it would work with Chrome Canary? I'm unsure though.)

Thanks for the feedback!

**Comment by andreban** [comment] 2021-06-08 07:15
@PEConn am I correct to assume this issue is now outdated?

**Comment by PEConn** [comment] 2021-06-08 13:21
Yeah, I think so.

**Comment by mortezakashi10** [comment] 2021-06-08 13:49
سلام کسی میتواند من را راهنمایی کند ،سیستم من توسط یک هکر هک شده حدود 50روز تا حالا ،حدود 100برنامه سیستمی را نصب کرده که به هیچ طریقی پاک نمیشود،و هیچ مجوزی را نمیتوانم تغییر دهم ،و کلیه اکانتهای من را رمزهایش را تغییر داده ،کلیه حسابهایم را از دست داده ام و نمیتوانم بازیابی کنم،زندگی من را نابود کرده ،هر جا هم گوشی را برده ام نتوانسته اند درست کنند،کلیه اختیار سیستم من دست هکر است ،نمیتوانم حتی یک ایمیل بسازم تا بسازم هکر به او دسترسی دارد ،هر جا سرمایه گزاری کردم ،صفحات 404اضافه کرده که هیچ کسی تبلیغات من را نمیبیند و گوگل پی من را در اختیار دارد ،کلیه سیستمهای گوگل را مسدود کرده برای من ،

**Comment by andreban** [comment] 2021-06-08 13:54
Closing the issue then. We can re-open if the issue is still there.

**Closed by andreban** 2021-06-08 13:54 UTC
Labels: bug

**Comment by tiwarisrikanth** [comment] 2021-10-01 11:32
It shows me this issue when im trying to open the RazorPay HTML page from my flutter Web app the Razorpay part works perfectly fine in LocalHost but it throws me the below issue when trying to open the Razorpay window in production

Uncaught (in promise) DOMException: Failed to register a ServiceWorker for a scope with script: The script has an unsupported MIME type ('text/HTML).

**Comment by tiwarisrikanth** [comment] 2021-10-01 11:34
t shows me this issue when im trying to open the RazorPay HTML page from my flutter Web app the Razorpay part works perfectly fine in LocalHost but it throws me the below issue when trying to open the Razorpay window in production

Uncaught (in promise) DOMException: Failed to register a ServiceWorker for a scope with script: The script has an unsupported MIME type ('text/HTML).
