### ISSUE TITLE
Custom-tabs-headers demo not sending unwhitelisted headers

### ISSUE THREAD

**Issue by EricTweeds** [GoogleChrome/android-browser-helper#198] opened 2020-10-20 15:38 UTC
**Describe the bug**
I ran the custom-tabs-headers example application locally and upon inspecting the network you can see that the unwhitelisted headers, "bearer-token" and "redirect-url" are not being sent in the header. I tested it with a whitelisted header ("accept-language") and the header value is updated in the network request. Also to note that the boolean result value returned from onRelationshipValidationResult is also false, indicating that the digital asset link was not verified. Is there a solution to this or a work around as this feature is important to the application I am working on?

**To Reproduce**
1. Build and run custom-tabs-headers demo via usb debug
2. On your browser open chrome://inspect
3. Find the custom tabs instance on the inspect page and inspect, click the button to launch the url and view the network logs
4. Network call "padr31.github.io", inspect the request headers, the custom headers are not present

**Expected behavior**
The digital asset link is validated and the custom headers are seen in the Request Headers of the network call

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - OS: Android 10
 - Browsers Installed Chrome 
 - Browser Versions 86.0.4240.99
 - android-browser-helper library version 1.3.2

**Comment by andreban** [comment] 2020-10-20 17:45
Hi @EricTweeds,

Custom headers will only work when the relationship between the app and the origin have been validated via Digital Asset Links - meaning you need to have control over the app and the web page opened by the app. There are more details in this blogpost: https://developers.google.com/web/android/custom-tabs/headers

**Comment by EricTweeds** [comment] 2020-10-20 18:16
Hi @andreban 

Thank you for your timely response, 
I have read and followed those instructions already and all attempts were unsuccessful. I am trying to resolve an issue with my company's production android application that broke in chrome update 83+ as it no longer allows the passing of non-whitelisted headers (Authorization header). 

After attempting to implement the digital asset links as described in the article https://developers.google.com/web/android/custom-tabs/headers, I decided to clone this repository and attempt to run the demo application (https://github.com/GoogleChrome/android-browser-helper/tree/master/demos/custom-tabs-headers) provided to see if it would work. Upon running the demo application I could see that it was also experiencing the same issues I was facing.

From what I can tell it appears to be issues validating a digital asset link relation of "delegate_permission/common.use_as_origin" (which the article says to use). I can confirm the digital asset link works since if I change the relation to 
"delegate_permission/common.handle_all_urls" I get a confirmation of validation. I also have made sure to use the correct CustomTabsService Relation on the application side for each case (CustomTabsService.RELATION_USE_AS_ORIGIN and CustomTabsService.RELATION_HANDLE_ALL_URLS)

**Comment by royerdavid** [comment] 2021-02-01 18:42
Any update on this issue? I'm experiencing a similar problem which would be a blocker for our project.

**Comment by andreban** [comment] 2021-02-03 15:20
I can confirm the feature works:

I created [this test web app](https://custom-tabs-custom-he.glitch.me/)  [[source](https://glitch.com/edit/#!/custom-tabs-custom-he)] and I can confirm I can see the custom headers coming through:

![Screenshot_20210203-151353](https://user-images.githubusercontent.com/1733592/106767547-e1587200-6632-11eb-8d17-a1f4b57adf71.png)


This is the diff from the demo project:

```diff
@@ -35,7 +35,7 @@ import android.widget.Button;
 import android.widget.Toast;
 
 public class MainActivity extends Activity {
-    private static final Uri URL = Uri.parse("https://padr31.github.io/");
+    private static final Uri URL = Uri.parse("https://custom-tabs-custom-he.glitch.me/");
 
     private CustomTabsSession mSession;
     private CustomTabsServiceConnection mConnection;
```

**Comment by andreban** [comment] 2021-02-05 15:49
Closing as the issue is not reproducible. Please, re open if there's more information that can help us reproduce.

**Closed by andreban** 2021-02-05 15:49 UTC

**Comment by GoldaEV** [comment] 2021-04-06 11:16
help with adding custom headers 
![photo_2021-04-06_14-05-30](https://user-images.githubusercontent.com/9753571/113701764-3ff8a580-96e1-11eb-8241-a55a0217bb84.jpg)  this is a screenshot from an example. 
My code doesn't work either.
in Mainifest.xml
`<meta-data android:name="asset_statements" android:resource="@string/asset_statements" />`
in string.xml
`<string name="asset_statements" translatable="false">[{ \"include\": \"https://qwerty.com/.well-known/assetlinks.json\" }] </string>`

file from site: https://qwerty.com/.well-known/assetlinks.json
`[{
  "relation": ["delegate_permission/common.use_as_origin"],
  "target" : { "namespace": "android_app", "package_name": "my.app.android",
               "sha256_cert_fingerprints": ["52:52:52:52:36:D9:4E:F3:DB:E5:3E:0E:7A:2D:3C:D8:08:8E:7A:FF:56:FC:30:E0:59:AC:05:43:CE:CE:CE:CE"] }
}]`
the rest of the code is as in the example [(https://developer.chrome.com/docs/android/custom-tabs/headers/)]

**Comment by Saicharan-Gontla** [comment] 2022-02-07 15:37
Hii, I am also facing the same issue. I am not getting the non white listed headers. Did any one find the solution?

**Comment by nehaberwal** [comment] 2022-12-15 11:37
Hi Team,
Facing the same issue - custom headers are not visible.

@andreban Please verify the details.

**Assetlink json link** : https://glitch.com/edit/#!/fishy-secret-butter?path=public%2F.well-known%2Fassetlinks.json%3A2%3A3

added the same in the manifest.

 mSession.validateRelationship(
                    CustomTabsService.RELATION_USE_AS_ORIGIN,
                    URLVal, null
                ) - getting true for this

Request URL: https://fishy-secret-butter.glitch.me/
Request Method: GET
Status Code: 200 
Remote Address: 3.216.72.21:443
Referrer Policy: strict-origin-when-cross-origin
content-length: 1955
content-type: text/html; charset=utf-8
date: Thu, 15 Dec 2022 11:23:46 GMT
etag: W/"7a3-39p6o8uI5d02X6IUAjjHRrHeGhY"
x-powered-by: Express
:authority: fishy-secret-butter.glitch.me
:method: GET
:path: /
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
cache-control: no-cache
content-language: content-language
pragma: no-cache
referer: android-app://com.freecharge.android.debug/
sec-ch-ua: "Not?A_Brand";v="8", "Chromium";v="108", "Google Chrome";v="108"
sec-ch-ua-mobile: ?1
sec-ch-ua-platform: "Android"
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: none
sec-fetch-user: ?1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Linux; Android 11; HD1901) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36
